from __future__ import annotations

from .models import AgentDefinition


def build_default_agent_definitions() -> list[AgentDefinition]:
    return [
        AgentDefinition(
            agent_id="research",
            name_cn="调研 Agent",
            name_en="Research Scout",
            mission="持续收集工业 AI、可穿戴边缘计算、RAG、竞品和客户痛点信息。",
            responsibilities=(
                "拆解目标行业、客户角色和高 ROI 场景。",
                "追踪 GitHub、论文、政策、招投标和竞品动态。",
                "把外部信息转成 WearEdge Pro 的产品假设和验证问题。",
            ),
            input_signals=("行业关键词", "客户访谈", "GitHub/论文链接", "竞品清单"),
            output_artifacts=("research_brief.md", "competitor_matrix.csv", "opportunity_backlog.md"),
            required_fields=("Insight", "Evidence", "Risk", "NextAction"),
            research_queries=(
                "industrial AI agents local first RAG",
                "wearable edge AI manufacturing maintenance",
                "industrial multimodal agent SOP quality inspection",
            ),
            handoff_targets=("productization", "algorithm", "sales"),
        ),
        AgentDefinition(
            agent_id="algorithm",
            name_cn="算法优化 Agent",
            name_en="Model Optimization Lead",
            mission="让端侧多模态模型、RAG 和结构化输出在低功耗硬件上稳定运行。",
            responsibilities=(
                "选择模型、量化策略、上下文预算和检索策略。",
                "设计结构化输出、ensure_keys、重试和置信度估计。",
                "压测 tokens/s、首 token 延迟、召回率和幻觉风险。",
            ),
            input_signals=("模型规格", "端侧硬件约束", "SOP/日志/质检数据", "延迟目标"),
            output_artifacts=("model_benchmark.json", "retrieval_eval.md", "schema_contract.yaml"),
            required_fields=("ModelPlan", "LatencyBudget", "SchemaContract", "EvalMetric"),
            research_queries=("edge VLM quantization", "RAG evaluation industrial documents", "structured output schema retry"),
            handoff_targets=("architecture", "fullstack", "productization"),
        ),
        AgentDefinition(
            agent_id="architecture",
            name_cn="分布式架构 Agent",
            name_en="Distributed Systems Architect",
            mission="设计边缘设备、网关、知识库、Agent 编排和企业系统接入架构。",
            responsibilities=(
                "定义端侧、现场网关和企业后台的职责边界。",
                "设计 TriggerFlow 风格的分支、并发、黑板和恢复机制。",
                "规划 MES、ERP、SCADA、PLC 和权限系统的安全接入。",
            ),
            input_signals=("设备拓扑", "网络限制", "系统接口", "安全等级"),
            output_artifacts=("architecture.md", "sequence_diagram.mmd", "api_gateway_spec.yaml"),
            required_fields=("ComponentMap", "DataFlow", "FailureMode", "IntegrationPoint"),
            research_queries=("edge gateway industrial AI architecture", "SCADA MES AI agent integration", "event driven workflow agent"),
            handoff_targets=("fullstack", "compliance", "hardware"),
        ),
        AgentDefinition(
            agent_id="fullstack",
            name_cn="全栈开发 Agent",
            name_en="Full Stack Builder",
            mission="把 Agent 能力做成可演示、可调试、可交付的软件界面和 API。",
            responsibilities=(
                "实现 CLI、API、控制台、数据导入和演示脚本。",
                "保持配置、Prompt、服务层、领域契约和测试分离。",
                "为 PoC 快速生成可跑通的端到端 Demo。",
            ),
            input_signals=("产品流程", "API 契约", "数据样例", "验收脚本"),
            output_artifacts=("api_server.py", "operator_console", "demo_script.md", "tests/"),
            required_fields=("BuildPlan", "Endpoint", "TestCase", "DemoPath"),
            research_queries=("local first RAG CLI API", "industrial agent dashboard", "operator assistant UX"),
            handoff_targets=("productization", "sales", "media"),
        ),
        AgentDefinition(
            agent_id="hardware",
            name_cn="硬件可制造性 Agent",
            name_en="DFM Hardware Lead",
            mission="把算力大脑、AR 眼镜、骨传导耳机和供电散热方案推向可制造状态。",
            responsibilities=(
                "分析 BOM、功耗、散热、接口、结构和供应链风险。",
                "规划腰包级边缘盒子、PD 供电、热插拔电池和工业防护。",
                "把硬件约束反馈给模型、架构和产品 Agent。",
            ),
            input_signals=("BOM", "功耗测试", "结构尺寸", "环境等级", "供应商资料"),
            output_artifacts=("bom_risk.md", "thermal_budget.csv", "dfm_checklist.md"),
            required_fields=("BOMRisk", "PowerBudget", "ThermalPlan", "ManufacturingNextStep"),
            research_queries=("wearable edge AI hardware DFM", "industrial AR glasses IP67", "edge AI module power thermal"),
            handoff_targets=("algorithm", "architecture", "compliance"),
        ),
        AgentDefinition(
            agent_id="productization",
            name_cn="工业场景产品化 Agent",
            name_en="Industrial Product Manager",
            mission="把工厂 SOP、质检、巡检、维修和工单流程变成可交付产品模块。",
            responsibilities=(
                "定义用户旅程、任务闭环、异常路径和人机确认点。",
                "把老师傅经验、SOP、控制计划和现场限制转成 Agent 工作流。",
                "设计高 ROI 场景的 PoC 验收指标。",
            ),
            input_signals=("客户现场", "SOP", "质检规范", "维修日志", "安全要求"),
            output_artifacts=("poc_scope.md", "workflow_map.mmd", "acceptance_criteria.md"),
            required_fields=("UseCase", "Workflow", "AcceptanceMetric", "HumanApproval"),
            research_queries=("industrial SOP AI assistant", "quality inspection AR workflow", "maintenance copilot manufacturing"),
            handoff_targets=("fullstack", "sales", "compliance"),
        ),
        AgentDefinition(
            agent_id="compliance",
            name_cn="合规与安全认证 Agent",
            name_en="Compliance and Safety Gatekeeper",
            mission="确保数据安全、工业安全、认证材料和责任边界能支撑进厂交付。",
            responsibilities=(
                "梳理本地化部署、数据分级、日志审计和权限控制要求。",
                "检查 IP 等级、跌落、电磁兼容、防爆和安全停机边界。",
                "输出客户合规问答、风险声明和安全审批材料。",
            ),
            input_signals=("客户安全规范", "部署架构", "硬件规格", "数据清单"),
            output_artifacts=("security_review.md", "certification_gap.md", "customer_faq.md"),
            required_fields=("ComplianceScope", "SafetyBoundary", "AuditLog", "ApprovalGate"),
            research_queries=("industrial AI safety compliance local deployment", "IEC industrial wearable safety", "factory data security AI"),
            handoff_targets=("architecture", "hardware", "sales"),
        ),
        AgentDefinition(
            agent_id="sales",
            name_cn="销售 BD 与客户成功 Agent",
            name_en="BD and Customer Success Lead",
            mission="把技术能力转化为 PoC、报价、客户跟进、ROI 和长期合作。",
            responsibilities=(
                "识别灯塔客户、决策链和预算归属。",
                "生成 PoC 方案、ROI 测算、报价结构和试点复盘。",
                "把客户反馈转为产品需求和交付风险。",
            ),
            input_signals=("客户名单", "痛点访谈", "报价约束", "PoC 结果"),
            output_artifacts=("poc_proposal.md", "roi_calculator.csv", "followup_plan.md"),
            required_fields=("CustomerPain", "ROIModel", "PoCScope", "FollowUp"),
            research_queries=("industrial AI ROI maintenance quality inspection", "manufacturing AI pilot proposal", "enterprise PoC customer success"),
            handoff_targets=("productization", "media", "compliance"),
        ),
        AgentDefinition(
            agent_id="media",
            name_cn="自媒体与融资叙事 Agent",
            name_en="Media and Fundraising Storyteller",
            mission="把 Ryan Hui 一人九 Agent 的工业创业故事讲清楚，持续吸引客户、伙伴和资本。",
            responsibilities=(
                "生成 GitHub README、公众号、短视频脚本、路演稿和投资人 Q&A。",
                "把技术进展转译成客户能理解的商业价值。",
                "维护 AI-Native Solo Founder 的可信叙事和发布节奏。",
            ),
            input_signals=("项目进展", "Demo 结果", "客户反馈", "赛事/融资节点"),
            output_artifacts=("launch_post.md", "pitch_deck_outline.md", "investor_qa.md"),
            required_fields=("Narrative", "ProofPoint", "Audience", "CallToAction"),
            research_queries=("AI native solo founder startup narrative", "industrial AI fundraising pitch", "technical founder build in public"),
            handoff_targets=("sales", "research", "Founder"),
        ),
    ]
